[package]
name = "ludogame"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "libraries/players",
]

[lib]
name = "game"
path = "src/game.rs"

[dependencies]
board = { path = "libraries/board" }
players = { path = "libraries/players" }
yew = "0.20.0"
