[package]
name = "players"
version = "1.0.0"
edition = "2021"

[lib]
name = "players"
path = "src/players.rs"

[dependencies]
pieces = { path = "../pieces" }
dice = { path = "../dice" }
board = { path = "../board", version = "1.0.0"}
rand = "0.8.4"
prettytable-rs = "0.10.0"
tui-rs = "0.1.0"