[package]
name = "players"
version = "2.0.0"
edition = "2021"

[lib]
name = "players"
path = "src/players.rs"

[dependencies]
pieces = { path = "../pieces" }
dice = { path = "../dice" }
board = { path = "../board" }
rand = "0.8.4"
