[package]
name = "board"
version = "2.0.0"
edition = "2021"

[lib]
name = "board"
path = "src/board.rs"

[dependencies]
rand = { version = "0.8.4", features = ["std"] }
pieces = { path = "../pieces" }
